use sub_db;
insert into video_sequence (vid_id,lang, content,start,end) values (5,"en", "english",100,2000);
insert into video_sequence (vid_id,lang, content,start,end) values (5,"en", "Hello World",2100,4000);
insert into video_sequence (vid_id,lang, content,start,end) values (5,"en", "Sample",4100,6000);
insert into video_sequence (vid_id,lang, content,start,end) values (5,"de", "deutsch",100,2000);
insert into video_sequence (vid_id,lang, content,start,end) values (5,"de", "Hallo Welt",2100,4000);
insert into video_sequence (vid_id,lang, content,start,end) values (5,"de", "Beispiel",4100,6000);
insert into video_sequence (vid_id,lang, content,start,end) values (6,"en", "english",100,2000);
insert into video_sequence (vid_id,lang, content,start,end) values (6,"en", "message",2100,4000);
insert into video_sequence (vid_id,lang, content,start,end) values (6,"en", "today",4100,6000);
insert into video_sequence (vid_id,lang, content,start,end) values (6,"de", "deutsch",100,2000);
insert into video_sequence (vid_id,lang, content,start,end) values (6,"de", "Nachricht",2100,4000);
insert into video_sequence (vid_id,lang, content,start,end) values (6,"de", "heute",4100,6000);
