# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 2, 8, 8, 42, 8000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
