# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='password',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
